# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: KMUMSA
email: kmumedstudent@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: /msasite # the subpath of your site, e.g. /blog
url: http://hsuyr.github.io # the base hostname & protocol for your site
twitter_username:
github_username:
facebook_username: kmumed
address: 高雄市三民區十全一路100號
slogan: 
feedback_form_url: http://goo.gl/forms/870g1nollN
equip_borrowing_form_url: http://goo.gl/forms/oUHGlifFNi

# Build settings
markdown: kramdown
cards-column: 3
collections:
  team:
    output: true
